---
name: "Main pipeline"
run-name: "Main pipfline on ${{ github.ref_name }}, github sha [${{ github.sha }}]"

"on":
  pull_request: {}
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: "testing"

jobs:
  some:
    name: "some job"
    runs-on: "self-hosted"
    defaults:
      run:
        shell: "bash"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

  deploy:
    needs: [some]
    uses: "./.github/workflows/02-deploy.yml"
    with:
      environment: ${{ inputs.environment }}
