---
name: "Main pipeline"
run-name: "Main pipfline on ${{ github.ref_name }}, github sha [${{ github.sha }}]"

"on":
  push: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  some:
    name: "some job"
    runs-on: "self-hosted"
    defaults:
      run:
        shell: "bash"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

  deploy:
    needs: [some]
    uses: "./.github/workflows/02-deploy.yml"
    with:
      environment: "testing"
