---
name: "Main pipeline"
run-name: "Main pipfline on [${{ github.ref_name }}]"

"on":
  workflow_dispatch:
    inputs:
      config:
        description: "Configuration to deploy"
        type: environment
        default: dev
  # push: {}

jobs:
  reused:
    uses: ./.github/workflows/01-reused.yml
    with:
      runs-on: "self-hosted"
      config: "dev"
    secrets: inherit
