---
name: "Main pipeline"
run-name: "Main pipfline on [${{ github.ref_name }}]"

"on":
  workflow_dispatch: {}
  push: {}

jobs:
  jobA:
    runs-on: self-hosted
    steps:
      - name: Failed 1
        id: failed1
        if: failure()
        run: |
          false

      - name: Failed 2
        id: failed2
        if: failure()
        run: |
          false

      - name: Check status
        if: failure()
        env:
          content: ${{ toJSON(steps) }}
        run: |
          echo $content
