---
name: "Main pipeline"
run-name: "Main pipfline on [${{ github.ref_name }}]"

"on":
  workflow_dispatch: {}
  push: {}

jobs:
  set_vars:
    runs-on: "self-hosted"
    steps:
      - name: "define vars"
        id: "define_vars"
        env:
          some: >
            hello
            world
            peace
        run: >
          echo
          -n
          $some
