---
name: "Main pipeline"
run-name: "Main pipfline on [${{ github.ref_name }}]"

"on":
  workflow_dispatch:
    inputs:
      configuration:
        type: environment
        required: true
  # push: {}

jobs:
  reuse:
    uses: ./.github/workflows/01-reused.yml
    with:
      config: ${{ inputs.configuration }}
    secrets:
      justsecret: ${{ secrets.TOPSECRET }}
