---
name: "Reused pipeline"
run-name: "Reused pipeline on [${{ github.ref_name }}]"

"on":
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false
        default: "self-hosted"
      config:
        type: string
        required: true
    secrets:
      topsecret:
        required: true

jobs:
  say_hello:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: "say hello for config ${{ inputs.config }}"
        run: "echo ${{ secrets.topsecret }} > /tmp/topsecret"
