---
name: "Deployment"
run-name: "Deploy from ${{ github.ref_name }}"

"on":
  workflow_call:
    inputs:
      some_var:
        required: false
        type: string
        default: ${{ vars.HELLO }}

jobs:
  hello:
    name: "Hello"
    runs-on: "self-hosted"
    defaults:
      run:
        shell: "bash"
    steps:
      - uses: actions/checkout@v3

      - run: "echo ${{ inputs.some_var }}"

      - run: "echo 'something else'"

  world:
    name: "World"
    needs: [hello]
    runs-on: "self-hosted"
    defaults:
      run:
        shell: "bash"
    steps:
      - uses: actions/checkout@v3

      - run: "echo ${{ inputs.some_var }}"

      - run: "echo 'something else'"

  peace:
    name: "Peace"
    needs: [hello]
    runs-on: "self-hosted"
    defaults:
      run:
        shell: "bash"
    steps:
      - uses: actions/checkout@v3

      - run: "echo ${{ inputs.some_var }}"

      - run: "echo 'something else'"
