---
name: "Deploy and app"
run-name: "Deploy from ${{ github.ref_name }}"

"on":
  workflow_call:
    inputs:
      some_var:
        required: false
        type: string
        default: "hello"

jobs:
  hello:
    name: "Hello"
    runs-on: "self-hosted"
    defaults:
      run:
        shell: "bash"
    steps:
      - uses: actions/checkout@v3

      - run: "echo ${{ inputs.some_var }}"

      - run: "echo 'something else'"
