name: "App_a and common"

"on":
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  prepare:
    name: "Check and prepare environment"
    runs-on: "self-hosted"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: "Check environment"
        run: echo "::notice::Here should be environment check"

  build:
    name: "Build artifacts"
    runs-on: "self-hosted"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
