name: "App_b and common"

"on":
  push:
    branches:
      - main
    paths:
      - "app_b/**"
      - "common"

jobs:
  main:
    runs-on: "self-hosted"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
