---
name: "Main pipeline"
run-name: "Main pipeline on ${{ github.ref_name }} for ${{ github.ref }}"

"on":
  push: {}
  pull_request: {}

jobs:
  some:
    name: "some job"
    runs-on: "self-hosted"
    defaults:
      run:
        shell: "bash"
    steps:
      - uses: actions/checkout@v3
