name: "RunMe"
run-name: "RunMe"

"on":
  workflow_dispatch:
    inputs:
      environ:
        description: "Run on environemnt"
        type: environment
        required: true
        default: "staging"

env:
  file_path: "testdata.json"
  run_on_env: "${{ inputs.environ }}"

jobs:
  say_hello:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v3

      - name: "chack environment"
        id: "check_env"
        shell: bash
        run: |
          ids=$(python3 get_scenario.py -f testdata.json -e ${run_on_env})
          echo "scenarioIDs=${ids}" >> $GITHUB_OUTPUT

      - name: "check if steps"
        shell: bash
        run: echo ${{ fromJSON(steps) }}
