name: "RunMe"
run-name: "RunMe"

"on":
  push: {}

env:
  file_path: "testdata.json"

jobs:
  say_hello:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v3

      - name: "Read JSON file"
        id: "read_json"
        shell: bash
        run: |
          pwd
          ls -lah
          cat ${{ env.file_path }}
          echo "json_content=$(cat ${{ env.file_path }})" >> "$GITHUB_OUTPUT"

      - name: "Dump JSON file content"
        id: "dump_json"
        shell: bash
        # run: "echo ${{ toJSON(steps.read_json.outputs.json_content) }}"
        run: "echo ${{ steps.read_json.outputs.json_content }}"

  say_goodby:
    runs-on: "self-hosted"
    steps:
      - name: "I just want to say goodby"
        id: "saygoodby"
        run: "echo goodby"
        shell: bash
