name: "RunMe"
run-name: "RunMe"

"on":
  workflow_dispatch:
    inputs:
      environemnt:
        description: "Run on environemnt"
        type: environment

env:
  file_path: "testdata.json"
  run_on_env: ${{ inputs.environment }}

jobs:
  say_hello:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v3

      - name: "chack environment"
        id: "check_env"
        shell: bash
        run: "echo ${{ env.run_on_env }}"
