---
name: "Main pipeline"
run-name: "Main pipfline on ${{ github.ref_name }}"

"on":
  # push: {}
  pull_request: {}

jobs:
  some:
    name: "some job"
    runs-on: "self-hosted"
    defaults:
      run:
        shell: "bash"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Deploy app"
        uses: "https://github.com/igor-sarychev/workflow_test/blob/feature/.github/workflows/deploy.yml@feature"
        with:
          some_var: "Hello world"
