name: "RunMe"
run-name: "RunMe"

"on":
  push: {}

env:
  file_path: "testdata.json"

jobs:
  say_hello:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v3

      - name: "Read JSON file"
        id: "read_json"
        shell: bash
        run: |
          json_content=$(cat ${{ env.file_path }})
          echo ${{ toJSON(${json_content}) }}
