name: "RunMe"

"on":
  workflow_dispatch: {}

env:
  file_path: "./testdata.json"

jobs:
  say_hello:
    runs-on: "self-hosted"
    steps:
      - name: "Read JSON file"
        id: "read_json"
        shell: bash
        run: |
          echo "json_content=$(cat ${{ env.file_path }})" >> "$GITHUB_OUTPUT"

      - name: "Dump JSON file content"
        id: "dump_json"
        shell: bash
        run: "echo ${{ toJSON(steps.read_json.outputs.json_content) }}"

  say_goodby:
    runs-on: "self-hosted"
    steps:
      - name: "I just want to say goodby"
        id: "saygoodby"
        run: "echo goodby"
        shell: bash
